### ISSUE TITLE
tm 安装后工作不正常没有数据

### ISSUE THREAD

**Issue by bikegl** [MacLeek/trackmac#2]
@MacLeek 很喜欢你这个小程序, 但是在我的机器上运行有问题
表现:
1.  从 github 上 clone 到本地 安装后没有数据(不能正常记录)
2. 从 github 上 clone 到本地 手动执行 python app.py 工作正常, 可以正常记录数据(没有报错)

也就是说使用原代码调试的方法在我的机器上是可以正常工作的

**Comment by MacLeek** [comment]
我是用brew安装的python，你应该是用的apple原生的版本吧？pip是用easy_install安装的吗？

**Comment by uuair** [comment]
我有两个错误，第一个是mac自带的python，版本是2.7.10，使用pip install trackmac安装错误如下：
error: could not create '/Library/Python/2.7/site-packages/trackmac': Permission denied

```
----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/ky/cz6z7yb16xvfz66w1w1mcmr00000gn/T/pip-build-X8a8K3/trackmac/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/ky/cz6z7yb16xvfz66w1w1mcmr00000gn/T/pip-lAYlVO-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ky/cz6z7yb16xvfz66w1w1mcmr00000gn/T/pip-build-X8a8K3/trackmac/

这个权限问题，如果使用sudo是可以克服的，但是sudo之后，程序在普通用户中，tm setup && tm start后产生天不了数据。

我机器中安装了pyenv，通过pyenv安装了python 2.7.11，切换后可以提示需要更新pip，更新后顺利安装，但是tm setup这里出现提示：
-bash: /usr/local/bin/tm: No such file or directory

是虚拟目录的问题吧。。。

所以卡在这里无法正常运行了。

**Comment by MacLeek** [comment]
@bikegl @uuair 找到原因了。如果是使用apple原生的python因为一些系统路径的问题，让我在plist这个文件里的bin位置错了，请先删掉~/Library/Application\ support\com.github.macleek.trackmac和~/Library/LaunchAgents/com.github.macleek.trackmac.plist，然后pip uninstall trackmac && pip install trackmac试一下把

**Comment by bikegl** [comment]
@MacLeek 如你所说问题解决了
